apiVersion: v1
kind: Pod
metadata:
  name: kubecon-postgress-pod
  labels:
    app.kubernetes.io/name: KubeConPostgress
spec:
  containers:
  - name: postgress
    image: laurentgoderre689/postgres-distroless
    securityContext:
      runAsUser: 70
      runAsGroup: 70
    volumeMounts:
    - name: db
      mountPath: /var/lib/postgresql/data/
  # initContainers:
  # - name: init-postgress
  #   image: postgres:alpine3.18
  #   env:
  #     - name: POSTGRES_PASSWORD
  #       valueFrom:
  #         secretKeyRef:
  #           name: kubecon-postgress-admin-pwd
  #           key: password
  #   command: ['docker-ensure-initdb.sh']
  #   volumeMounts:
  #   - name: db
  #     mountPath: /var/lib/postgresql/data/
  volumes:
  - name: db
    emptyDir: {}
    